# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from fdpg_runtime.layers import FDCConv, FDCResidual, ShallowPositionInject

# Register protected FDPG classes on the historical module path so existing
# configs and checkpoints remain compatible with the full local framework.
from . import block as _block
from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2f_FDConv,
    C2f_FDConvLite,
    C2f_LFDC,
    # LFDCBlock
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CAAResidual,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    FDBottleneck,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    LSKAttentionResidual,
    LSKResidual,
    MaxSigmoidAttnBlock,
    PolyKernelResidual,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    SpatialGateResidual,
    TorchVision,
)
from .conv import (
    CBAM,
    AdaptiveConcat2,
    AdaptiveConcat3,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
    WeightedConcat2,
    WeightedConcat3,
)
from .Converse2D import Converse2D
from .ESSamp import ESSamp
from .EUCB import EUCB
from .head import (
    OBB,
    Classify,
    Detect,
    LRPCHead,
    Pose,
    RTDETRDecoder,
    Segment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    v10Detect,
)
from .L_FDC import LFDCBlock
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

_block.FDCConv = FDCConv
_block.FDCResidual = FDCResidual
_block.ShallowPositionInject = ShallowPositionInject

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "DFL",
    "ELAN1",
    "EUCB",
    "MLP",
    "OBB",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "AdaptiveConcat2",
    "AdaptiveConcat3",
    "Attention",
    "BNContrastiveHead",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAttn",
    "C2fCIB",
    "C2fPSA",
    "C2f_FDConv",
    "C2f_FDConvLite",
    "C2f_LFDC",
    "C3Ghost",
    "C3k2",
    "C3x",
    "CAAResidual",
    "CBFuse",
    "CBLinear",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "Converse2D",
    "DWConv",
    "DWConvTranspose2d",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    # "LFDCBlock",
    "ESSamp",
    "FDBottleneck",
    "FDCConv",
    "FDCResidual",
    "Focus",
    "GhostBottleneck",
    "GhostConv",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "Index",
    "LRPCHead",
    "LSKAttentionResidual",
    "LSKResidual",
    "LayerNorm2d",
    "LightConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "PolyKernelResidual",
    "Pose",
    "Proto",
    "RTDETRDecoder",
    "RepC3",
    "RepConv",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "Segment",
    "ShallowPositionInject",
    "SpatialAttention",
    "SpatialGateResidual",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WeightedConcat2",
    "WeightedConcat3",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
    "v10Detect",
)
